# @package _global_
name: LeNet
arch:
  _target_: srcs.model.lenet.LeNet
  num_classes: 25
loss:
  _target_: srcs.model.loss.focal_loss
optimizer:
  _target_: torch.optim.Adam
  lr: ${learning_rate}
  weight_decay: ${weight_decay}
  amsgrad: true
lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: ${scheduler_step_size}
  gamma: ${scheduler_gamma}
